import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export type PokeResults = {
  PokeResults: [{ name: string; url: string }];
};
const Home: NextPage<{ results: PokeResults["PokeResults"] }> = ({
  results,
}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Welcome to the PokeDex</h1>
        {results?.map((p, i) => {
          return (
            <div key={p.name}>
              <Link href={`/pokemon/${p.name}`} passHref={true}>
                <h4>{p.name}</h4>
              </Link>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export const getStaticProps = async () => {
  const res = await fetch("https://pokeapi.co/api/v2/pokemon/?limit=150");
  const { results } = await res.json();

  return {
    props: { results },
  };
};

export default Home;
